---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:emdsn/gitops-demo
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: rcww/podinfo
      tag: dev-ggp9dpsy
    replicaCount: 1
    hpa:
      enabled: false
